
package formularios;
import Cita.FormularioCitas;
import Empresa.frmInternalEliminarEmpresa;
import Empresa.frmInternalModificarEmpresa;
import Empresa.frmInternalInsertarEmpresa;
import Empresa.frmInternalBuscarEmpresa;
import Evento.formularioEvento;
import Evento.inscripcionEmpresa;
import Mesa.AsignarMesaEmpresa;
import Mesa.MesaForm;
import Participante.frmParticipante;
import Rubro.formularioRubro;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author juan
 */
public class frmMenuAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuAdministrador
     */
    public frmMenuAdministrador() {
        initComponents();
    }

    private frmMenuAdministrador(Dimension screenSize) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar7 = new javax.swing.JMenuBar();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenuBar8 = new javax.swing.JMenuBar();
        jMenu16 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        panelAdministrador = new javax.swing.JDesktopPane();
        valoresIniciales = new javax.swing.JMenuBar();
        btnSalir = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btnInsertarEmpr = new javax.swing.JMenuItem();
        btnBuscarEmpr = new javax.swing.JMenuItem();
        btnModificarEmpr = new javax.swing.JMenuItem();
        btnEliminarEmpr = new javax.swing.JMenuItem();
        BarraRubro = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu18 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        btnEvento = new javax.swing.JMenu();
        registrarE = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu19 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu20 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("File");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar4.add(jMenu9);

        jMenu10.setText("File");
        jMenuBar5.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar5.add(jMenu11);

        jMenu12.setText("File");
        jMenuBar6.add(jMenu12);

        jMenu13.setText("Edit");
        jMenuBar6.add(jMenu13);

        jMenuItem2.setText("jMenuItem2");

        jMenu14.setText("File");
        jMenuBar7.add(jMenu14);

        jMenu15.setText("Edit");
        jMenuBar7.add(jMenu15);

        jMenu16.setText("File");
        jMenuBar8.add(jMenu16);

        jMenu17.setText("Edit");
        jMenuBar8.add(jMenu17);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelAdministradorLayout = new javax.swing.GroupLayout(panelAdministrador);
        panelAdministrador.setLayout(panelAdministradorLayout);
        panelAdministradorLayout.setHorizontalGroup(
            panelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 928, Short.MAX_VALUE)
        );
        panelAdministradorLayout.setVerticalGroup(
            panelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        btnSalir.setText("Archivo");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        btnSalir.add(jMenuItem1);

        valoresIniciales.add(btnSalir);

        jMenu3.setText("Empresa");

        btnInsertarEmpr.setText("Registrar");
        btnInsertarEmpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarEmprActionPerformed(evt);
            }
        });
        jMenu3.add(btnInsertarEmpr);

        btnBuscarEmpr.setText("Buscar");
        btnBuscarEmpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEmprActionPerformed(evt);
            }
        });
        jMenu3.add(btnBuscarEmpr);

        btnModificarEmpr.setText("Modificar");
        btnModificarEmpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEmprActionPerformed(evt);
            }
        });
        jMenu3.add(btnModificarEmpr);

        btnEliminarEmpr.setText("Eliminar");
        btnEliminarEmpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEmprActionPerformed(evt);
            }
        });
        jMenu3.add(btnEliminarEmpr);

        valoresIniciales.add(jMenu3);

        BarraRubro.setText("Rubro");
        BarraRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraRubroActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Rubro");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        BarraRubro.add(jMenuItem3);

        valoresIniciales.add(BarraRubro);

        jMenu18.setText("Citas");

        jMenuItem4.setText("Citas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu18.add(jMenuItem4);

        valoresIniciales.add(jMenu18);

        btnEvento.setText("Evento");
        btnEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEventoMouseClicked(evt);
            }
        });
        btnEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventoActionPerformed(evt);
            }
        });

        registrarE.setText("Registrar Evento");
        registrarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarEActionPerformed(evt);
            }
        });
        btnEvento.add(registrarE);

        jMenuItem7.setText("Inscribir Empresa");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        btnEvento.add(jMenuItem7);

        valoresIniciales.add(btnEvento);

        jMenu19.setText("Mesa");

        jMenuItem5.setText("Añadir Mesa");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu19.add(jMenuItem5);

        jMenuItem6.setText("Asignar Mesa");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu19.add(jMenuItem6);

        valoresIniciales.add(jMenu19);

        jMenu20.setText("Participante");

        jMenuItem8.setText("Registrar Participante");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu20.add(jMenuItem8);

        valoresIniciales.add(jMenu20);

        setJMenuBar(valoresIniciales);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAdministrador)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAdministrador)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    /*
    
     private void btnInsertarEmprActionPerformed(java.awt.event.ActionEvent evt) {                                                
        frmInternalInsertarEmpresa insertar = new frmInternalInsertarEmpresa();
       panelAdministrador.add(insertar);
       insertar.show();
    }                                               

    private void btnBuscarEmprActionPerformed(java.awt.event.ActionEvent evt) {                                              
        frmInternalBuscarEmpresa insertar = new frmInternalBuscarEmpresa();
       panelAdministrador.add(insertar);
       insertar.show();
    }                                             

    private void btnModificarEmprActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        frmInternalModificarEmpresa insertar = new frmInternalModificarEmpresa();
       panelAdministrador.add(insertar);
       insertar.show();
    }                                                

    private void btnEliminarEmprActionPerformed(java.awt.event.ActionEvent evt) {                                                
         frmInternalEliminarEmpresa insertar = new frmInternalEliminarEmpresa();
       panelAdministrador.add(insertar);
       insertar.show();
    }
    */ 
    private void btnInsertarEmprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarEmprActionPerformed
        frmInternalInsertarEmpresa insertar = new frmInternalInsertarEmpresa();
       panelAdministrador.add(insertar);
       insertar.show();
    }//GEN-LAST:event_btnInsertarEmprActionPerformed

    private void btnBuscarEmprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEmprActionPerformed
        frmInternalBuscarEmpresa insertar = new frmInternalBuscarEmpresa();
       panelAdministrador.add(insertar);
       insertar.show();
    }//GEN-LAST:event_btnBuscarEmprActionPerformed

    private void btnModificarEmprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEmprActionPerformed
         frmInternalModificarEmpresa insertar = new frmInternalModificarEmpresa();
       panelAdministrador.add(insertar);
       insertar.show();
    }//GEN-LAST:event_btnModificarEmprActionPerformed

    private void btnEliminarEmprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmprActionPerformed
       frmInternalEliminarEmpresa insertar = new frmInternalEliminarEmpresa();
       panelAdministrador.add(insertar);
       insertar.show();
    }//GEN-LAST:event_btnEliminarEmprActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(1);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void BarraRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraRubroActionPerformed
       
    }//GEN-LAST:event_BarraRubroActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        formularioRubro rubro = new formularioRubro();
        panelAdministrador.add(rubro);
        rubro.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       FormularioCitas cita = new FormularioCitas();
       panelAdministrador.add(cita);
       cita.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEventoMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnEventoMouseClicked

    private void btnEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventoActionPerformed
        
    }//GEN-LAST:event_btnEventoActionPerformed

    private void registrarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarEActionPerformed
        Evento.formularioEvento evento = new formularioEvento();
        panelAdministrador.add(evento);
        evento.show();
    }//GEN-LAST:event_registrarEActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Mesa.MesaForm evento = new MesaForm();
        panelAdministrador.add(evento);
        evento.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Mesa.AsignarMesaEmpresa evento = new AsignarMesaEmpresa();
        panelAdministrador.add(evento);
        evento.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        Evento.inscripcionEmpresa evento = new inscripcionEmpresa();
        panelAdministrador.add(evento);
        evento.show();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Participante.frmParticipante evento = new frmParticipante();
        panelAdministrador.add(evento);
        evento.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try 
                {
                    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                    new frmMenuAdministrador().setVisible(true);
                    } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu BarraRubro;
    private javax.swing.JMenuItem btnBuscarEmpr;
    private javax.swing.JMenuItem btnEliminarEmpr;
    private javax.swing.JMenu btnEvento;
    private javax.swing.JMenuItem btnInsertarEmpr;
    private javax.swing.JMenuItem btnModificarEmpr;
    private javax.swing.JMenu btnSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuBar jMenuBar7;
    private javax.swing.JMenuBar jMenuBar8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JDesktopPane panelAdministrador;
    private javax.swing.JMenuItem registrarE;
    private javax.swing.JMenuBar valoresIniciales;
    // End of variables declaration//GEN-END:variables
}
